### ISSUE TITLE
Latest Twig needs to use latest slf4j-api

### ISSUE THREAD

**Issue by bjorstrom** [clojusc/twig#2]
Coati builds with the latest Twig (0.2.4) are currently failing. 

Per the instructions given at http://www.slf4j.org/codes.html (section "java.lang.NoClassDefFoundError: org/slf4j/event/LoggingEvent") , updating with the following should work:

```
[org.slf4j/slf4j-api "1.7.21"]
```
